### ISSUE TITLE
Particle Tracking Workflow

### ISSUE THREAD

**Issue by gmerritt123** [gmerritt123/ROW_TASKS#9]
Idea is to build a routine for executing particle tracking and possibly SWAT analysis on any given dac file. dac files will be generated via RunModel.py, risk assessment related exports are generated via WSSU_Tool_DataPrep.py.

Tasks:

- [x] ensure dac has 'PT_Poro' 
- [x] load dac
- [ ] Backward particle tracking
    - [x] Generate backward particle release locations
    - [x] Municipal wells only etc. 
    - [x] 25 m radius, 25 particles per ring, start with top/middle/bottom of screen
    - [x] find WT at top ring release locations, where top ring release locations is above WT, move down to WT
    - [x] Adjust middle ring commensurately
    - [x] execute particle tracking and attribute
    - [x] Some routine for cutting out unsat zone:
        - [x] use id_layer_shifts to ID when particles move in/out of the unsat zone
        - [x] define some threshold length or time spent consecutively in unsat zone to flag as when particle should be truncated
    - [x] create 3D lines, binned by 2, 5, 25 year travel
    - [ ] TBD --> how to translate into WHPA polygons --> concave hull with QA steps, varying alpha by wellfield, vs "rasterization"
- [ ] Forward particle tracking
    - [x] release grid over domain (find WT)
    - [x] receptor polygons
    - [x] execute forward PT
    - [x] join to receptor polygons
    - [x] trim to captured particles
    - [x] attribute those and export for potential SWAT analysis
    - [x] 2, 5, 25 year calculated from time of capture
    - [x] create 3D lines
    - [ ] TBD --> how to translate into WHPA polygons --> concave hull with QA steps, varying alpha by wellfield, vs "rasterization"

Key exports:
 - Attributed Backward particles
 - Attributed Forward particles (captured only)
 - Backward binned lines
 - Forward binned lines
